import { json, type MetaFunction } from '@remix-run/cloudflare';
import { Header } from '~/components/header/Header';
import { Footer } from '~/components/ui/Footer';
import BackgroundRays from '~/components/ui/BackgroundRays';

export const meta: MetaFunction = () => {
  return [
    { title: 'Terms of Service - Sloth Coder' },
    { name: 'description', content: 'Terms of Service for Sloth Coder' },
  ];
};

export const loader = () => json({});

export default function Terms() {
  return (
    <div className="flex flex-col min-h-screen bg-bolt-elements-background-depth-1">
      <BackgroundRays />
      <Header />
      <main className="flex-grow container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl font-bold text-bolt-elements-textPrimary mb-8">Terms of Service</h1>

          <section className="mb-8">
            <p className="text-bolt-elements-textSecondary mb-4">
              Welcome to Sloth Coder. By accessing or using our service, you agree to be bound by these Terms of
              Service.
            </p>
            <p className="text-bolt-elements-textSecondary">
              Please read these terms carefully before using our platform. If you do not agree with any part of these
              terms, you may not use our service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-bolt-elements-textPrimary mb-4">1. Service Description</h2>
            <p className="text-bolt-elements-textSecondary mb-4">
              Sloth Coder provides an integrated development environment (IDE) and AI-powered code generation tools. Our
              service is designed to assist developers in writing, testing, and deploying code more efficiently.
            </p>
            <p className="text-bolt-elements-textSecondary">
              While we strive to provide accurate and helpful code suggestions, users are responsible for reviewing and
              testing all generated code before implementation in production environments.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-bolt-elements-textPrimary mb-4">2. User Accounts</h2>
            <p className="text-bolt-elements-textSecondary mb-4">
              To access certain features of our service, you may need to create an account. You are responsible for
              maintaining the confidentiality of your account credentials and for all activities that occur under your
              account.
            </p>
            <p className="text-bolt-elements-textSecondary">
              You agree to notify us immediately of any unauthorized use of your account or any other breach of
              security. We cannot and will not be liable for any loss or damage arising from your failure to comply with
              this provision.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-bolt-elements-textPrimary mb-4">3. Intellectual Property</h2>
            <p className="text-bolt-elements-textSecondary mb-4">
              The Sloth Coder service, including all content, features, and functionality, is owned by us and is
              protected by international copyright, trademark, patent, trade secret, and other intellectual property
              laws.
            </p>
            <p className="text-bolt-elements-textSecondary mb-4">
              You retain ownership of any code you create or upload to our platform. However, by using our AI code
              generation features, you grant us permission to analyze your code to improve our services.
            </p>
            <p className="text-bolt-elements-textSecondary">
              Code generated by our AI tools is provided under an open license, allowing you to use it freely in your
              projects, unless otherwise specified.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-bolt-elements-textPrimary mb-4">4. Acceptable Use</h2>
            <p className="text-bolt-elements-textSecondary mb-4">You agree not to use Sloth Coder to:</p>
            <ul className="list-disc pl-6 mb-4 text-bolt-elements-textSecondary space-y-2">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe upon the rights of others</li>
              <li>Generate malicious code or engage in harmful activities</li>
              <li>Attempt to gain unauthorized access to our systems or user accounts</li>
              <li>Interfere with or disrupt the integrity or performance of our service</li>
              <li>Engage in any activity that could harm our reputation or business</li>
            </ul>
            <p className="text-bolt-elements-textSecondary">
              We reserve the right to terminate or suspend access to our service for violations of these acceptable use
              policies.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-bolt-elements-textPrimary mb-4">5. Limitation of Liability</h2>
            <p className="text-bolt-elements-textSecondary mb-4">
              To the maximum extent permitted by law, Sloth Coder and its affiliates shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of
              profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or
              inability to access or use the service.
            </p>
            <p className="text-bolt-elements-textSecondary">
              We specifically disclaim liability for any issues arising from the use of AI-generated code in production
              environments without proper testing and review.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-bolt-elements-textPrimary mb-4">6. Changes to Terms</h2>
            <p className="text-bolt-elements-textSecondary mb-4">
              We reserve the right to modify these Terms of Service at any time. We will provide notice of significant
              changes by posting the new terms on our website or through other communication channels.
            </p>
            <p className="text-bolt-elements-textSecondary">
              Your continued use of Sloth Coder after such changes constitutes your acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-bolt-elements-textPrimary mb-4">7. Contact Us</h2>
            <p className="text-bolt-elements-textSecondary">
              If you have any questions about these Terms of Service, please contact us at support@slothcoder.com.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
